// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACPlCDltfTj6wpUD_mV6C9sYy5Q8g7Zmo',
    appId: '1:717329057146:web:306d2f7c9e6618af2ec2c3',
    messagingSenderId: '717329057146',
    projectId: 'brilho-azul',
    authDomain: 'brilho-azul.firebaseapp.com',
    storageBucket: 'brilho-azul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGaVzzd-4QhN5DZUTmdIVi9nwm0JHqPCI',
    appId: '1:717329057146:android:755b39b823b66b242ec2c3',
    messagingSenderId: '717329057146',
    projectId: 'brilho-azul',
    storageBucket: 'brilho-azul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXoSbFUj5UkM499_jyiJEkSEgh2IU8ds',
    appId: '1:717329057146:ios:9f5939a8eb931f742ec2c3',
    messagingSenderId: '717329057146',
    projectId: 'brilho-azul',
    storageBucket: 'brilho-azul.firebasestorage.app',
    iosBundleId: 'com.example.brilhoAzulLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXoSbFUj5UkM499_jyiJEkSEgh2IU8ds',
    appId: '1:717329057146:ios:9f5939a8eb931f742ec2c3',
    messagingSenderId: '717329057146',
    projectId: 'brilho-azul',
    storageBucket: 'brilho-azul.firebasestorage.app',
    iosBundleId: 'com.example.brilhoAzulLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACPlCDltfTj6wpUD_mV6C9sYy5Q8g7Zmo',
    appId: '1:717329057146:web:4172513945208bad2ec2c3',
    messagingSenderId: '717329057146',
    projectId: 'brilho-azul',
    authDomain: 'brilho-azul.firebaseapp.com',
    storageBucket: 'brilho-azul.firebasestorage.app',
  );
}
